### ISSUE TITLE
Bug: Windowing is not operating currectly with RocksDb

### ISSUE THREAD

**Issue by eneshoxha** [buildersoftio/cortex#43]
There is a bug showing in Windows when we do look, the error is as follows.

```bash
Emitted Activity: Login
Emitted Activity: ViewDashboard
Unhandled exception. System.Threading.LockRecursionException: Recursive read lock acquisitions not allowed in this mode.
   at System.Threading.ReaderWriterLockSlim.TryEnterReadLockCore(TimeoutTracker timeout)
   at System.Threading.ReaderWriterLockSlim.EnterReadLock()
   at Cortex.States.RocksDb.RocksDbStateStore`2.Get(TKey key)
   at Cortex.Streams.Operators.SessionWindowOperator`3.CheckForInactiveSessions()
   at Cortex.Streams.Operators.SessionWindowOperator`3.<.ctor>b__14_0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Emitted Activity: ClickButton

C:\Users\enesh\source\repos\CortexExamplesWiki\CortexExamplesWiki\bin\Debug\net8.0\CortexExamplesWiki.exe (process 16816) exited with code -532462766 (0xe0434352).
Press any key to close this window . . .
```

**Comment by eneshoxha** [comment]
Moved to feature #47
